// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Keep an in-memory cache of the current user ID to avoid repeated auth calls
let _currentUserId: string | null = null;

export function setCurrentUserId(id: string | null) {
  _currentUserId = id;
}

export function getCurrentUserId(): string | null {
  return _currentUserId;
}

function createSupabaseClient(): SupabaseClient<Database> {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      '❌ VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY deben estar definidas en .env\n' +
      'Copia .env.example a .env y completa las credenciales de tu proyecto Supabase.'
    );
  }
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: { storage: localStorage, persistSession: true, autoRefreshToken: true },
  });
}

let _supabase: SupabaseClient<Database> | null = null;
try {
  _supabase = createSupabaseClient();
} catch (err) {
  console.error('Supabase no disponible:', (err as Error).message);
}

// Proxy: si supabase no está inicializado, muestra error claro en cada llamada
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop) {
    if (!_supabase) {
      throw new Error(
        'Supabase no está disponible. ' +
        'Asegúrate de tener un archivo .env con VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY.'
      );
    }
    return (_supabase as any)[prop];
  }
});

/**
 * Ensures an anonymous auth session exists.
 * Call this once on app startup after the user unlocks the app.
 * Anonymous auth provides proper data isolation via RLS policies.
 */
export async function ensureAnonymousSession(): Promise<string | null> {
  try {
    // Use getUser() which validates the JWT with the server.
    // getSession() only reads from cache and doesn't detect expired tokens.
    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      setCurrentUserId(user.id);
      return user.id;
    }

    const { data, error } = await supabase.auth.signInAnonymously();
    if (error) {
      console.error('Failed to create anonymous session:', error.message);
      return null;
    }
    const uid = data.user?.id ?? null;
    setCurrentUserId(uid);
    return uid;
  } catch (err) {
    console.error('Auth initialization error:', err);
    return null;
  }
}

/** Get the current user ID, or null if not authenticated */
export async function getUserId(): Promise<string | null> {
  try {
    const { data: { user } } = await supabase.auth.getUser();
    if (user?.id) setCurrentUserId(user.id);
    return user?.id ?? null;
  } catch {
    return null;
  }
}

/**
 * Helper to add user_id filter to any query.
 * Call this for every SELECT/INSERT/UPDATE/DELETE to ensure data isolation.
 */
export function withUserId<T extends Record<string, unknown>>(
  item: T,
  userId: string | null
): T & { user_id?: string } {
  if (!userId) return item as T & { user_id?: string };
  return { ...item, user_id: userId };
}

/**
 * Creates a filter condition for the current user.
 */
export function userFilter(userId: string | null) {
  return userId ? { user_id: userId } : {};
}